### PR TITLE
Fix Quad.copy constructor not copying point3 correctly

### LINKED ISSUE #221: Quad.copy discards point3
```
  /// Create a quad as a copy of [other].
  Quad.copy(Quad other)
      : _point0 = new Vector3.copy(other._point0),
        _point1 = new Vector3.copy(other._point1),
        _point2 = new Vector3.copy(other._point2),
        _point3 = new Vector3.copy(other._point2);
```

It should be:

```
       _point3 = new Vector3.copy(other._point3);
```

### PR DESCRIPTION
**Pull request by Fox32**
Fixes #221

### CODE REVIEW

**Comment by Fox32** [comment]
@kevmoo can you take a look at this one?

**Comment by kevmoo** [comment]
Good find!

**Review by kevmoo — APPROVED** [review]

**Comment by kevmoo** [comment]
Published as 2.1.2! Thanks for the fix!

**Comment by Fox32** [comment]
Thanks for taking a look

**Pull request merged**
