### PR TITLE
Fix more Dart 2 core library constant names.

### PR DESCRIPTION
**Pull request by munificent**
I'm not sure how these got missed on the first go around, but here's the rest of them.

Thanks!

### CODE REVIEW

**Comment by munificent** [comment]
I bumped the pubspec version in this change, but I don't have permission to publish it. Would you mind pushing it to pub too? Thanks!

**Comment by tvolkert** [comment]
I noticed a few days ago that I don't have permission to publish either ☹️

**Comment by munificent** [comment]
I think @leafpetersen can roll it from GitHub, so that's OK.

**Comment by leafpetersen** [comment]
I already rolled internally.  External users will presumably get broken when Dart 2 lands though.

**Comment by johnmccutchan** [comment]
I've given tvolkert@google.com permission to release vector_math.dart packages on pub.

**Comment by lexaknyazev** [comment]
Could examples in the README be also updated to use lower-case constants?

**Comment by munificent** [comment]
Thanks, @johnmccutchan!

**Pull request merged**
