### PR TITLE
Vector.angleTo and angleToSigned

### PR DESCRIPTION
**Pull request by Fox32**
This methods were already available on Vector3, but I'm missing them on Vector2.

### CODE REVIEW

**Comment by Fox32** [comment]
@johnmccutchan Bump :)

**Comment by johnmccutchan** [comment]
Hi, please rebase and then I can merge it. Thanks!

**Comment by Fox32** [comment]
@johnmccutchan  Done

**Comment by johnmccutchan** [comment]
Thanks!

**Pull request merged**
