### PR TITLE
Vector*.random constuctor

### PR DESCRIPTION
**Pull request by hermanbergwerf**
See #170 
The code generation tool has added some code to the 64bit float library that did not exists before (someone forgot to run it?). The formatting of some parts is also altered since I ran `dartfmt`.

### CODE REVIEW

**Comment by hermanbergwerf** [comment]
I have signed the Google CLA now.

**Comment by johnmccutchan** [comment]
What is with the unnecessary formatting changes?

**Comment by hermanbergwerf** [comment]
I used `dartfmt`, and the previous commits apparently didn't. `dartfmt` adds some kind of line breaks after comments. I would say it's generally a good idea to stick to the Dart style conventions.

**Comment by hermanbergwerf** [comment]
If you want I can create a branch that is not formatted.

**Comment by johnmccutchan** [comment]
Hi,

Sorry I forgot about this pull request. Can you refresh it and I'll take another look?

Thanks,
John

**Comment by hermanbergwerf** [comment]
Do you want me to take out the formatting? As I said I use a tool that runs dartfmt on my entire dart directory, and some parts of this project were manually formatted. But I can take them out.

**Comment by johnmccutchan** [comment]
Keep the formatting but keep it as a separate commit.

**Comment by johnmccutchan** [comment]
@hermanbergwerf You need to update the CL so that I can merge it.

**Comment by hermanbergwerf** [comment]
I know, I'm very busy these weeks, sorry. I'll look into it ASAP.

Op do 28 jul. 2016 om 09:44 schreef John McCutchan <notifications@github.com

**Comment by hermanbergwerf** [comment]
I figured it would be easier to overwrite my fork. I have not used `dartfmt` so there are no formatting changes. I think those should be handled separately.

**Comment by johnmccutchan** [comment]
Thanks!

**Pull request merged**
