### PR TITLE
prep for merge into master

### PR DESCRIPTION
**Pull request by jakemac53**
- Update version
- Update sdk constraints
- Update travis config

### CODE REVIEW

**Comment by jakemac53** [comment]
Note that tests will be broken until https://github.com/dart-lang/test/pull/1283 is merged. So once that lands you can re-run travis here and it should pass, and then this can be merged.

**Comment by jakemac53** [comment]
@kevmoo can you restart travis?

**Comment by kevmoo** [comment]
@jakemac53 – done!

**Comment by jakemac53** [comment]
@kevmoo looks like you have to do the merging here

**Pull request merged**
