### PR TITLE
Fix rotation around Y axis

### PR DESCRIPTION
**Pull request by moritzblume**
Current implementation rotates clockwise which is not the norm and not consistent to the implemented X and Y rotation matrices.

This PR fixes issue #261 .

### CODE REVIEW

**Comment by moritzblume** [comment]
Any updates? When will it be merged?

**Comment by johnmccutchan** [comment]
Hi,

If you are still around I'd be interesting in merging this change.

**Comment by johnmccutchan** [comment]
Ping @moritzblume

**Comment by moritzblume** [comment]
Sure, go ahead! Do you need anything else from my side?

**Review by johnmccutchan — APPROVED** [review]

**Comment by kevmoo** [comment]
this is causing failures in CI! https://github.com/google/vector_math.dart/actions/runs/5602301361/job/15176578907#step:9:76

**Comment by johnmccutchan** [comment]
@moritzblume We discovered two issues with the CL and so we had to revert, please address the following:

1. Broke some tests (run `dart test` to reproduce)
2. Made rotateY inconsistent across Matrix3 and Matrix4 classes.

For issue (1) is pretty trivial, just swapping the signs in the test expectation.
For issue (2) both Matrix3 and Matrix4 need to be updated together so they are consistent.

**Pull request merged**
